# Generated by Django 4.1.6 on 2023-02-07 08:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('product_description', models.CharField(max_length=500)),
                ('stock', models.CharField(choices=[('available', 'available'), ('Not available', 'Not available')], default='available', max_length=25)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('product_image', models.ImageField(upload_to='media/images')),
                ('product_weight', models.IntegerField()),
            ],
        ),
    ]
